In [28]:
# main.ipynb
# Optional Jupyter Notebook for testing ETL step by step

# -------------------------------------------------------
# 1️⃣ Import Modules and DB Config
# -------------------------------------------------------
import pandas as pd
from config.db_config import get_connection

from extract.extract_students import extract_students
from extract.extract_courses import extract_courses
from extract.extract_faculty import extract_faculty
from extract.extract_enrollment import extract_enrollment

from transform.transform_students import transform_students
from transform.transform_courses import transform_courses
from transform.transform_faculty import transform_faculty
from transform.transform_enrollment import transform_enrollment

from load.load_students import load_students
from load.load_courses import load_courses
from load.load_faculty import load_faculty
from load.load_enrollment import load_enrollment

print("Modules imported successfully.")

Modules imported successfully.

In [29]:
# -------------------------------------------------------
# 2️⃣ Extract Data
# -------------------------------------------------------
df_students = extract_students()
df_courses = extract_courses()
df_faculty = extract_faculty()
df_enroll = extract_enrollment()

print("Extraction complete.")

Extracted 5 student records
Extracted 5 course records
Extracted 5 faculty records
Extracted 5 enrollment records
Extraction complete.

In [30]:
# View extracted data (optional)
df_students.head()

   student_id    full_name  age             major  year
0         101  Alice Smith   20  Computer Science     2
1         102  Bob Johnson   22           Physics     3
2         103    Clara Lee   19       Mathematics     1
3         104  David Brown   21         Chemistry     3
4         105   Emma Davis   20           Biology     2

In [31]:
df_courses.head()

  course_id        course_name        department  credits
0      C101    data structures  computer science        3
1      C102    quantum physics           physics        4
2      C103         calculus i       mathematics        3
3      C104  organic chemistry         chemistry        4
4      C105           genetics           biology        3

In [32]:
df_faculty.head()

  faculty_id            name        department      title
0        F01   Dr. Emily Ray  Computer Science  Professor
1        F02    Dr. John Kim           Physics   Lecturer
2        F03    Dr. Sara Lee       Mathematics  Professor
3        F04  Dr. Mark White         Chemistry   Lecturer
4        F05  Dr. Anna Green           Biology  Professor

In [33]:
df_enroll.head()

  enrollment_id  student_id course_id semester grade
0           E01         101      C101   Spring     A
1           E02         102      C102     Fall     B
2           E03         103      C103   Spring    A-
3           E04         104      C104     Fall    B+
4           E05         105      C105   Spring     A

In [34]:
# -------------------------------------------------------
# 3️⃣ Transform Data
# -------------------------------------------------------
df_students = transform_students(df_students)
df_courses = transform_courses(df_courses)
df_faculty = transform_faculty(df_faculty)
df_enroll = transform_enrollment(df_enroll)

print("Transformation complete.")

Transformed student data
Transformed course data
Transformed faculty data
Transformed enrollment data
Transformation complete.

In [35]:
# View transformed data (optional)
df_students.head()

   student_id    full_name  age             major  year
0         101  Alice Smith   20  Computer Science     2
1         102  Bob Johnson   22           Physics     3
2         103    Clara Lee   19       Mathematics     1
3         104  David Brown   21         Chemistry     3
4         105   Emma Davis   20           Biology     2

In [36]:
df_courses.head()

  course_id        course_name        department  credits
0      C101    Data Structures  Computer Science        3
1      C102    Quantum Physics           Physics        4
2      C103         Calculus I       Mathematics        3
3      C104  Organic Chemistry         Chemistry        4
4      C105           Genetics           Biology        3

In [37]:
df_faculty.head()

  faculty_id            name        department      title
0        F01   Dr. Emily Ray  Computer Science  Professor
1        F02    Dr. John Kim           Physics   Lecturer
2        F03    Dr. Sara Lee       Mathematics  Professor
3        F04  Dr. Mark White         Chemistry   Lecturer
4        F05  Dr. Anna Green           Biology  Professor

In [38]:
df_enroll.head()

  enrollment_id  student_id course_id semester grade
0           E01         101      C101   Spring     A
1           E02         102      C102     Fall     B
2           E03         103      C103   Spring    A-
3           E04         104      C104     Fall    B+
4           E05         105      C105   Spring     A

In [39]:
# -------------------------------------------------------
# 4️⃣ Load Data into PostgreSQL
# -------------------------------------------------------
load_students(df_students)
load_courses(df_courses)
load_faculty(df_faculty)
load_enrollment(df_enroll)

print("Loading complete. ETL pipeline finished!")
|

SyntaxError: invalid syntax (1272626503.py, line 10)

In [ ]:
# -------------------------------------------------------
# 4️⃣ Load Data into PostgreSQL
# -------------------------------------------------------
load_students(df_students)
load_courses(df_courses)
load_faculty(df_faculty)
load_enrollment(df_enroll)

print("Loading complete. ETL pipeline finished!")

Loaded student data
Loaded course data
Loaded faculty data
Loaded enrollment data
Loading complete. ETL pipeline finished!

In [ ]:
# -------------------------------------------------------
# 5️⃣ Verify Data in PostgreSQL (optional)
# -------------------------------------------------------
conn = get_connection()
cur = conn.cursor()

tables = ["students_table","courses_table","faculty_table","enrollment_table"]

for table in tables:
    print(f"\nContents of {table}:")
    cur.execute(f"SELECT * FROM {table};")
    rows = cur.fetchall()
    for row in rows:
        print(row)

cur.close()
conn.close()

Contents of students_table:
(101, 'Alice Smith', 20, 'Computer Science', 2)
(102, 'Bob Johnson', 22, 'Physics', 3)
(103, 'Clara Lee', 19, 'Mathematics', 1)
(104, 'David Brown', 21, 'Chemistry', 3)
(105, 'Emma Davis', 20, 'Biology', 2)

Contents of courses_table:
('C101', 'Data Structures', 'Computer Science', 3)
('C102', 'Quantum Physics', 'Physics', 4)
('C103', 'Calculus I', 'Mathematics', 3)
('C104', 'Organic Chemistry', 'Chemistry', 4)
('C105', 'Genetics', 'Biology', 3)

Contents of faculty_table:
('F01', 'Dr. Emily Ray', 'Computer Science', 'Professor')
('F02', 'Dr. John Kim', 'Physics', 'Lecturer')
('F03', 'Dr. Sara Lee', 'Mathematics', 'Professor')
('F04', 'Dr. Mark White', 'Chemistry', 'Lecturer')
('F05', 'Dr. Anna Green', 'Biology', 'Professor')

Contents of enrollment_table:
('E01', 101, 'C101', 'Spring', 'A')
('E02', 102, 'C102', 'Fall', 'B')
('E03', 103, 'C103', 'Spring', 'A-')
('E04', 104, 'C104', 'Fall', 'B+')
('E05', 105, 'C105', 'Spring', 'A')